# Scheme name: Deep Oceanic Next
# Scheme author: spearkkk (https://github.com/spearkkk)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Deep Oceanic Next.16
ColorForeground=#d4e1e8
ColorBackground=#001c1f
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#002931;#d3464d;#63b784;#f3b863;#568ccf;#d0658e;#4fb7ae;#e0e9ef;#001c1f;#e37552;#003640;#004852;#0093a3;#8b66d6;#d4e1e8;#f2f7f9
