name: Build colorschemes

on:
  push:
    branches: ['master']
  schedule:
    - cron: '28 1 * * *'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event.pusher.email != 'bot+base16-xfce4-terminal@afq984.org'
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Remove old colorschemes
      run: rm -r colorschemes
    
    - name: Create colorschemes/
      run: mkdir colorschemes

    - name: Build colorschemes
      run: go run build.go

    - name: Commit colorschemes
      run: |
        git add colorschemes/
        git config user.email bot+base16-xfce4-terminal@afq984.org
        git config user.name bot+base16-xfce4-terminal
        git diff --staged --exit-code --quiet || git commit -m "update $(date +%Y-%m-%d-%H-%M-%S)" -m "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"

    - name: Push colorschemes
      uses: ad-m/github-push-action@b007e7b818e33b04afd056e4c4b57ba917145d7a  # master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
